//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaDeNegocios.ServiciosDeFlipllo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/LogicaDeNegocios.ClasesDeDominio")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoDeVerificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicaDeNegocios.ServiciosDeFlipllo.EstadoUsuario EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreDeUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicaDeNegocios.ServiciosDeFlipllo.Puntuacion PuntuacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoDeVerificacion {
            get {
                return this.CodigoDeVerificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoDeVerificacionField, value) != true)) {
                    this.CodigoDeVerificacionField = value;
                    this.RaisePropertyChanged("CodigoDeVerificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicaDeNegocios.ServiciosDeFlipllo.EstadoUsuario Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDeUsuario {
            get {
                return this.NombreDeUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreDeUsuarioField, value) != true)) {
                    this.NombreDeUsuarioField = value;
                    this.RaisePropertyChanged("NombreDeUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicaDeNegocios.ServiciosDeFlipllo.Puntuacion Puntuacion {
            get {
                return this.PuntuacionField;
            }
            set {
                if ((object.ReferenceEquals(this.PuntuacionField, value) != true)) {
                    this.PuntuacionField = value;
                    this.RaisePropertyChanged("Puntuacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Puntuacion", Namespace="http://schemas.datacontract.org/2004/07/LogicaDeNegocios.ClasesDeDominio")]
    [System.SerializableAttribute()]
    public partial class Puntuacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ExperienciaTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PartidasJugadasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VictoriasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ExperienciaTotal {
            get {
                return this.ExperienciaTotalField;
            }
            set {
                if ((this.ExperienciaTotalField.Equals(value) != true)) {
                    this.ExperienciaTotalField = value;
                    this.RaisePropertyChanged("ExperienciaTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PartidasJugadas {
            get {
                return this.PartidasJugadasField;
            }
            set {
                if ((this.PartidasJugadasField.Equals(value) != true)) {
                    this.PartidasJugadasField = value;
                    this.RaisePropertyChanged("PartidasJugadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Victorias {
            get {
                return this.VictoriasField;
            }
            set {
                if ((this.VictoriasField.Equals(value) != true)) {
                    this.VictoriasField = value;
                    this.RaisePropertyChanged("Victorias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoUsuario", Namespace="http://schemas.datacontract.org/2004/07/LogicaDeNegocios.ClasesDeDominio")]
    public enum EstadoUsuario : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoValidado = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Registrado = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sesion", Namespace="http://schemas.datacontract.org/2004/07/ServiciosDeComunicacion.InterfacesDeServi" +
        "cios")]
    [System.SerializableAttribute()]
    public partial class Sesion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaActualizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicaDeNegocios.ServiciosDeFlipllo.Usuario UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Creacion {
            get {
                return this.CreacionField;
            }
            set {
                if ((this.CreacionField.Equals(value) != true)) {
                    this.CreacionField = value;
                    this.RaisePropertyChanged("Creacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaActualizacion {
            get {
                return this.UltimaActualizacionField;
            }
            set {
                if ((this.UltimaActualizacionField.Equals(value) != true)) {
                    this.UltimaActualizacionField = value;
                    this.RaisePropertyChanged("UltimaActualizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicaDeNegocios.ServiciosDeFlipllo.Usuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensaje", Namespace="http://schemas.datacontract.org/2004/07/ServiciosDeComunicacion.InterfacesDeServi" +
        "cios")]
    [System.SerializableAttribute()]
    public partial class Mensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuerpoDeMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDDeUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuerpoDeMensaje {
            get {
                return this.CuerpoDeMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.CuerpoDeMensajeField, value) != true)) {
                    this.CuerpoDeMensajeField = value;
                    this.RaisePropertyChanged("CuerpoDeMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDDeUsuario {
            get {
                return this.IDDeUsuarioField;
            }
            set {
                if ((this.IDDeUsuarioField.Equals(value) != true)) {
                    this.IDDeUsuarioField = value;
                    this.RaisePropertyChanged("IDDeUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosDeFlipllo.IServiciosDeFlipllo", CallbackContract=typeof(LogicaDeNegocios.ServiciosDeFlipllo.IServiciosDeFliplloCallback))]
    public interface IServiciosDeFlipllo {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeFlipllo/AutenticarUsuario")]
        void AutenticarUsuario(LogicaDeNegocios.ServiciosDeFlipllo.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeFlipllo/AutenticarUsuario")]
        System.Threading.Tasks.Task AutenticarUsuarioAsync(LogicaDeNegocios.ServiciosDeFlipllo.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosDeFlipllo/RegistrarUsuario", ReplyAction="http://tempuri.org/IServiciosDeFlipllo/RegistrarUsuarioResponse")]
        bool RegistrarUsuario(LogicaDeNegocios.ServiciosDeFlipllo.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosDeFlipllo/RegistrarUsuario", ReplyAction="http://tempuri.org/IServiciosDeFlipllo/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> RegistrarUsuarioAsync(LogicaDeNegocios.ServiciosDeFlipllo.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosDeFlipllo/ValidarCodigoDeUsuario", ReplyAction="http://tempuri.org/IServiciosDeFlipllo/ValidarCodigoDeUsuarioResponse")]
        bool ValidarCodigoDeUsuario(LogicaDeNegocios.ServiciosDeFlipllo.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosDeFlipllo/ValidarCodigoDeUsuario", ReplyAction="http://tempuri.org/IServiciosDeFlipllo/ValidarCodigoDeUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ValidarCodigoDeUsuarioAsync(LogicaDeNegocios.ServiciosDeFlipllo.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeFlipllo/ActualizarSesion")]
        void ActualizarSesion(LogicaDeNegocios.ServiciosDeFlipllo.Sesion sesion);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeFlipllo/ActualizarSesion")]
        System.Threading.Tasks.Task ActualizarSesionAsync(LogicaDeNegocios.ServiciosDeFlipllo.Sesion sesion);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeFlipllo/ConectarDelChat")]
        void ConectarDelChat(LogicaDeNegocios.ServiciosDeFlipllo.Sesion usuario);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeFlipllo/ConectarDelChat")]
        System.Threading.Tasks.Task ConectarDelChatAsync(LogicaDeNegocios.ServiciosDeFlipllo.Sesion usuario);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeFlipllo/DesconectarDelChat")]
        void DesconectarDelChat(int IDDeUsuario);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeFlipllo/DesconectarDelChat")]
        System.Threading.Tasks.Task DesconectarDelChatAsync(int IDDeUsuario);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeFlipllo/EnviarMensaje")]
        void EnviarMensaje(LogicaDeNegocios.ServiciosDeFlipllo.Mensaje mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeFlipllo/EnviarMensaje")]
        System.Threading.Tasks.Task EnviarMensajeAsync(LogicaDeNegocios.ServiciosDeFlipllo.Mensaje mensaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiciosDeFliplloCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeFlipllo/ActualizarListaDeUsuarios")]
        void ActualizarListaDeUsuarios(LogicaDeNegocios.ServiciosDeFlipllo.Sesion[] usuariosConectados);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeFlipllo/RecibirMensaje")]
        void RecibirMensaje(LogicaDeNegocios.ServiciosDeFlipllo.Mensaje mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeFlipllo/EnviarIDUsuario")]
        void EnviarIDUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeFlipllo/RecibirSesion")]
        void RecibirSesion(LogicaDeNegocios.ServiciosDeFlipllo.Sesion sesion);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeFlipllo/PedirActualizarSesion")]
        void PedirActualizarSesion();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiciosDeFliplloChannel : LogicaDeNegocios.ServiciosDeFlipllo.IServiciosDeFlipllo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosDeFliplloClient : System.ServiceModel.DuplexClientBase<LogicaDeNegocios.ServiciosDeFlipllo.IServiciosDeFlipllo>, LogicaDeNegocios.ServiciosDeFlipllo.IServiciosDeFlipllo {
        
        public ServiciosDeFliplloClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiciosDeFliplloClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiciosDeFliplloClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosDeFliplloClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosDeFliplloClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void AutenticarUsuario(LogicaDeNegocios.ServiciosDeFlipllo.Usuario usuario) {
            base.Channel.AutenticarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task AutenticarUsuarioAsync(LogicaDeNegocios.ServiciosDeFlipllo.Usuario usuario) {
            return base.Channel.AutenticarUsuarioAsync(usuario);
        }
        
        public bool RegistrarUsuario(LogicaDeNegocios.ServiciosDeFlipllo.Usuario usuario) {
            return base.Channel.RegistrarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarUsuarioAsync(LogicaDeNegocios.ServiciosDeFlipllo.Usuario usuario) {
            return base.Channel.RegistrarUsuarioAsync(usuario);
        }
        
        public bool ValidarCodigoDeUsuario(LogicaDeNegocios.ServiciosDeFlipllo.Usuario usuario) {
            return base.Channel.ValidarCodigoDeUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarCodigoDeUsuarioAsync(LogicaDeNegocios.ServiciosDeFlipllo.Usuario usuario) {
            return base.Channel.ValidarCodigoDeUsuarioAsync(usuario);
        }
        
        public void ActualizarSesion(LogicaDeNegocios.ServiciosDeFlipllo.Sesion sesion) {
            base.Channel.ActualizarSesion(sesion);
        }
        
        public System.Threading.Tasks.Task ActualizarSesionAsync(LogicaDeNegocios.ServiciosDeFlipllo.Sesion sesion) {
            return base.Channel.ActualizarSesionAsync(sesion);
        }
        
        public void ConectarDelChat(LogicaDeNegocios.ServiciosDeFlipllo.Sesion usuario) {
            base.Channel.ConectarDelChat(usuario);
        }
        
        public System.Threading.Tasks.Task ConectarDelChatAsync(LogicaDeNegocios.ServiciosDeFlipllo.Sesion usuario) {
            return base.Channel.ConectarDelChatAsync(usuario);
        }
        
        public void DesconectarDelChat(int IDDeUsuario) {
            base.Channel.DesconectarDelChat(IDDeUsuario);
        }
        
        public System.Threading.Tasks.Task DesconectarDelChatAsync(int IDDeUsuario) {
            return base.Channel.DesconectarDelChatAsync(IDDeUsuario);
        }
        
        public void EnviarMensaje(LogicaDeNegocios.ServiciosDeFlipllo.Mensaje mensaje) {
            base.Channel.EnviarMensaje(mensaje);
        }
        
        public System.Threading.Tasks.Task EnviarMensajeAsync(LogicaDeNegocios.ServiciosDeFlipllo.Mensaje mensaje) {
            return base.Channel.EnviarMensajeAsync(mensaje);
        }
    }
}
