//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoABaseDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjetoEnInventario
    {
        public int Id { get; set; }
        public System.DateTime FechaDeObtencion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Objeto Objeto { get; set; }
    }
}
