//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoABaseDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjetoEnCofre
    {
        public int Id { get; set; }
        public decimal ProbabilidadDeObtener { get; set; }
    
        public virtual Objeto Objeto { get; set; }
        public virtual Cofre Cofre { get; set; }
    }
}
