//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoABaseDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puntuacion
    {
        public int Id { get; set; }
        public int PartidasJugadas { get; set; }
        public int Victorias { get; set; }
        public long ExperienciaTotal { get; set; }
    
        public virtual Usuario Usuario { get; set; }

        public static implicit operator Puntuacion(int v)
        {
            throw new NotImplementedException();
        }
    }
}
