//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaDeNegocios.ServiciosDeComunicacion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/ServiciosDeComunicacion")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreDeUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicaDeNegocios.ServiciosDeComunicacion.Sesion SesionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDeUsuario {
            get {
                return this.NombreDeUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreDeUsuarioField, value) != true)) {
                    this.NombreDeUsuarioField = value;
                    this.RaisePropertyChanged("NombreDeUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicaDeNegocios.ServiciosDeComunicacion.Sesion Sesion {
            get {
                return this.SesionField;
            }
            set {
                if ((object.ReferenceEquals(this.SesionField, value) != true)) {
                    this.SesionField = value;
                    this.RaisePropertyChanged("Sesion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sesion", Namespace="http://schemas.datacontract.org/2004/07/ServiciosDeComunicacion")]
    [System.SerializableAttribute()]
    public partial class Sesion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosDeComunicacion.IAdministradorDeUsuarios")]
    public interface IAdministradorDeUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorDeUsuarios/ValidarCuenta", ReplyAction="http://tempuri.org/IAdministradorDeUsuarios/ValidarCuentaResponse")]
        bool ValidarCuenta(LogicaDeNegocios.ServiciosDeComunicacion.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorDeUsuarios/ValidarCuenta", ReplyAction="http://tempuri.org/IAdministradorDeUsuarios/ValidarCuentaResponse")]
        System.Threading.Tasks.Task<bool> ValidarCuentaAsync(LogicaDeNegocios.ServiciosDeComunicacion.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorDeUsuarios/RegistrarCuenta", ReplyAction="http://tempuri.org/IAdministradorDeUsuarios/RegistrarCuentaResponse")]
        bool RegistrarCuenta(LogicaDeNegocios.ServiciosDeComunicacion.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorDeUsuarios/RegistrarCuenta", ReplyAction="http://tempuri.org/IAdministradorDeUsuarios/RegistrarCuentaResponse")]
        System.Threading.Tasks.Task<bool> RegistrarCuentaAsync(LogicaDeNegocios.ServiciosDeComunicacion.Usuario usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministradorDeUsuariosChannel : LogicaDeNegocios.ServiciosDeComunicacion.IAdministradorDeUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministradorDeUsuariosClient : System.ServiceModel.ClientBase<LogicaDeNegocios.ServiciosDeComunicacion.IAdministradorDeUsuarios>, LogicaDeNegocios.ServiciosDeComunicacion.IAdministradorDeUsuarios {
        
        public AdministradorDeUsuariosClient() {
        }
        
        public AdministradorDeUsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministradorDeUsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorDeUsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorDeUsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidarCuenta(LogicaDeNegocios.ServiciosDeComunicacion.Usuario usuario) {
            return base.Channel.ValidarCuenta(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarCuentaAsync(LogicaDeNegocios.ServiciosDeComunicacion.Usuario usuario) {
            return base.Channel.ValidarCuentaAsync(usuario);
        }
        
        public bool RegistrarCuenta(LogicaDeNegocios.ServiciosDeComunicacion.Usuario usuario) {
            return base.Channel.RegistrarCuenta(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarCuentaAsync(LogicaDeNegocios.ServiciosDeComunicacion.Usuario usuario) {
            return base.Channel.RegistrarCuentaAsync(usuario);
        }
    }
}
