//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaDeNegocios.ServiciosDeJuego {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sesion", Namespace="http://schemas.datacontract.org/2004/07/ServiciosDeComunicacion.Interfaces.Interf" +
        "acesDeServiciosDeFlipllo")]
    [System.SerializableAttribute()]
    public partial class Sesion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaActualizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicaDeNegocios.ServiciosDeJuego.Usuario UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Creacion {
            get {
                return this.CreacionField;
            }
            set {
                if ((this.CreacionField.Equals(value) != true)) {
                    this.CreacionField = value;
                    this.RaisePropertyChanged("Creacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UltimaActualizacion {
            get {
                return this.UltimaActualizacionField;
            }
            set {
                if ((this.UltimaActualizacionField.Equals(value) != true)) {
                    this.UltimaActualizacionField = value;
                    this.RaisePropertyChanged("UltimaActualizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicaDeNegocios.ServiciosDeJuego.Usuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/LogicaDeNegocios.ClasesDeDominio")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoDeVerificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicaDeNegocios.ServiciosDeJuego.EstadoUsuario EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreDeUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicaDeNegocios.ServiciosDeJuego.Puntuacion PuntuacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoDeVerificacion {
            get {
                return this.CodigoDeVerificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoDeVerificacionField, value) != true)) {
                    this.CodigoDeVerificacionField = value;
                    this.RaisePropertyChanged("CodigoDeVerificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicaDeNegocios.ServiciosDeJuego.EstadoUsuario Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDeUsuario {
            get {
                return this.NombreDeUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreDeUsuarioField, value) != true)) {
                    this.NombreDeUsuarioField = value;
                    this.RaisePropertyChanged("NombreDeUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicaDeNegocios.ServiciosDeJuego.Puntuacion Puntuacion {
            get {
                return this.PuntuacionField;
            }
            set {
                if ((object.ReferenceEquals(this.PuntuacionField, value) != true)) {
                    this.PuntuacionField = value;
                    this.RaisePropertyChanged("Puntuacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Puntuacion", Namespace="http://schemas.datacontract.org/2004/07/LogicaDeNegocios.ClasesDeDominio")]
    [System.SerializableAttribute()]
    public partial class Puntuacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ExperienciaTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PartidasJugadasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VictoriasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ExperienciaTotal {
            get {
                return this.ExperienciaTotalField;
            }
            set {
                if ((this.ExperienciaTotalField.Equals(value) != true)) {
                    this.ExperienciaTotalField = value;
                    this.RaisePropertyChanged("ExperienciaTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PartidasJugadas {
            get {
                return this.PartidasJugadasField;
            }
            set {
                if ((this.PartidasJugadasField.Equals(value) != true)) {
                    this.PartidasJugadasField = value;
                    this.RaisePropertyChanged("PartidasJugadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Victorias {
            get {
                return this.VictoriasField;
            }
            set {
                if ((this.VictoriasField.Equals(value) != true)) {
                    this.VictoriasField = value;
                    this.RaisePropertyChanged("Victorias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoUsuario", Namespace="http://schemas.datacontract.org/2004/07/LogicaDeNegocios.ClasesDeDominio")]
    public enum EstadoUsuario : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Indefinido = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inexistente = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CodigoDeValidacionNovalido = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Registrado = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActualmenteConectado = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ficha", Namespace="http://schemas.datacontract.org/2004/07/LogicaDeNegocios.ClasesDeDominio")]
    [System.SerializableAttribute()]
    public partial class Ficha : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicaDeNegocios.ServiciosDeJuego.ColorDeFicha ColorActualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicaDeNegocios.ServiciosDeJuego.ColorDeFicha ColorAnteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FueGiradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Windows.Point PosicionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicaDeNegocios.ServiciosDeJuego.ColorDeFicha ColorActual {
            get {
                return this.ColorActualField;
            }
            set {
                if ((this.ColorActualField.Equals(value) != true)) {
                    this.ColorActualField = value;
                    this.RaisePropertyChanged("ColorActual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicaDeNegocios.ServiciosDeJuego.ColorDeFicha ColorAnterior {
            get {
                return this.ColorAnteriorField;
            }
            set {
                if ((this.ColorAnteriorField.Equals(value) != true)) {
                    this.ColorAnteriorField = value;
                    this.RaisePropertyChanged("ColorAnterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FueGirada {
            get {
                return this.FueGiradaField;
            }
            set {
                if ((this.FueGiradaField.Equals(value) != true)) {
                    this.FueGiradaField = value;
                    this.RaisePropertyChanged("FueGirada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Windows.Point Posicion {
            get {
                return this.PosicionField;
            }
            set {
                if ((this.PosicionField.Equals(value) != true)) {
                    this.PosicionField = value;
                    this.RaisePropertyChanged("Posicion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ColorDeFicha", Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum ColorDeFicha : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Negro = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blanco = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ninguno = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosDeJuego.IServiciosDeJuego", CallbackContract=typeof(LogicaDeNegocios.ServiciosDeJuego.IServiciosDeJuegoCallback))]
    public interface IServiciosDeJuego {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosDeJuego/TirarFicha", ReplyAction="http://tempuri.org/IServiciosDeJuego/TirarFichaResponse")]
        bool TirarFicha(LogicaDeNegocios.ServiciosDeJuego.Sesion sesion, System.Windows.Point point);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosDeJuego/TirarFicha", ReplyAction="http://tempuri.org/IServiciosDeJuego/TirarFichaResponse")]
        System.Threading.Tasks.Task<bool> TirarFichaAsync(LogicaDeNegocios.ServiciosDeJuego.Sesion sesion, System.Windows.Point point);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeJuego/PedirActualizacionDeTablero")]
        void PedirActualizacionDeTablero(LogicaDeNegocios.ServiciosDeJuego.Sesion sesion);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeJuego/PedirActualizacionDeTablero")]
        System.Threading.Tasks.Task PedirActualizacionDeTableroAsync(LogicaDeNegocios.ServiciosDeJuego.Sesion sesion);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeJuego/ActualizarCanalDeCallback")]
        void ActualizarCanalDeCallback(LogicaDeNegocios.ServiciosDeJuego.Sesion sesion);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeJuego/ActualizarCanalDeCallback")]
        System.Threading.Tasks.Task ActualizarCanalDeCallbackAsync(LogicaDeNegocios.ServiciosDeJuego.Sesion sesion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiciosDeJuegoCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeJuego/RecibirTablero")]
        void RecibirTablero(LogicaDeNegocios.ServiciosDeJuego.Ficha[] tablero);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeJuego/TerminarJuego")]
        void TerminarJuego(int experenciaPorPuntos, int experenciaPorFichas, bool ganaste);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiciosDeJuego/RecibirTirada")]
        void RecibirTirada(System.Windows.Point tirada);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiciosDeJuegoChannel : LogicaDeNegocios.ServiciosDeJuego.IServiciosDeJuego, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosDeJuegoClient : System.ServiceModel.DuplexClientBase<LogicaDeNegocios.ServiciosDeJuego.IServiciosDeJuego>, LogicaDeNegocios.ServiciosDeJuego.IServiciosDeJuego {
        
        public ServiciosDeJuegoClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiciosDeJuegoClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiciosDeJuegoClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosDeJuegoClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosDeJuegoClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool TirarFicha(LogicaDeNegocios.ServiciosDeJuego.Sesion sesion, System.Windows.Point point) {
            return base.Channel.TirarFicha(sesion, point);
        }
        
        public System.Threading.Tasks.Task<bool> TirarFichaAsync(LogicaDeNegocios.ServiciosDeJuego.Sesion sesion, System.Windows.Point point) {
            return base.Channel.TirarFichaAsync(sesion, point);
        }
        
        public void PedirActualizacionDeTablero(LogicaDeNegocios.ServiciosDeJuego.Sesion sesion) {
            base.Channel.PedirActualizacionDeTablero(sesion);
        }
        
        public System.Threading.Tasks.Task PedirActualizacionDeTableroAsync(LogicaDeNegocios.ServiciosDeJuego.Sesion sesion) {
            return base.Channel.PedirActualizacionDeTableroAsync(sesion);
        }
        
        public void ActualizarCanalDeCallback(LogicaDeNegocios.ServiciosDeJuego.Sesion sesion) {
            base.Channel.ActualizarCanalDeCallback(sesion);
        }
        
        public System.Threading.Tasks.Task ActualizarCanalDeCallbackAsync(LogicaDeNegocios.ServiciosDeJuego.Sesion sesion) {
            return base.Channel.ActualizarCanalDeCallbackAsync(sesion);
        }
    }
}
